name: Complex
env:
  WORKSPACE_ENVIRONMENT_VARIABLE: 'custom workspace environment variable'
  ARTIFACT_NAME: 'myartifact'
on: push
jobs:
  ubuntu: 
    runs-on: ubuntu-latest
    steps:
    - name: ubuntu Date
      run: |
        echo The UBUNTU Date is
        date
  windows:
    env:
      JOB_ENVIRONMENT_VARIABLE: 'custom job environment variable for windows'
    runs-on: windows-latest
    steps:
    - name: Print custom environment variables from windows-latest
      run: |
        date
        echo "Accessing environment variables in run command"
        echo "$Env:WORKSPACE_ENVIRONMENT_VARIABLE"
        echo "$Env:JOB_ENVIRONMENT_VARIABLE"
        echo "$Env:ARTIFACT_NAME"
        echo "$Env:STEP_ENVIRONMENT_VARIABLE"
        echo "------------------------------------------------------"
        echo "Accessing environment variables using env context"
        echo "${{ env.WORKSPACE_ENVIRONMENT_VARIABLE }}"
        echo "${{ env.JOB_ENVIRONMENT_VARIABLE }}"
        echo "${{ env.ARTIFACT_NAME }}"
        echo "${{ env.STEP_ENVIRONMENT_VARIABLE }} Not defined"
  macos:
    runs-on: macos-latest
    steps:
    - run: date
  depends:
    needs: [ubuntu,macos,windows]
    runs-on: macos-latest
    steps:
    - name: depends after run
      run: |
        date
        ls
        java -version
