name: Complex
on: push
jobs:
  ubuntu: 
    runs-on: ubuntu-latest
    steps:
    - name: ubuntu Date
      run: |
        echo The UBUNTU Date is
        date
  windows:
    runs-on: windows-latest
    steps:
    - run: date
  macos:
    runs-on: macos-latest
    steps:
    - run: date
  depends:
    needs: [ubuntu,macos,windows]
    runs-on: macos-latest
    steps:
    - name: depends after run
      run: date
